import { escape } from "./ui.js";
export function renderPayload(draft, container) {
  if (draft.type === "workflow") {
    const steps = draft.payload.steps;
    container.innerHTML = `<section class="editor-section"><div class="section-title"><h2>Steps</h2><span id="step-progress">${steps.filter((s) => s.done).length} / ${steps.length} complete</span></div><ol class="workflow-steps">${steps.map((step, i) => `<li><span class="step-number">${i + 1}</span><input type="checkbox" data-step-done="${i}" aria-label="Complete step ${i + 1}" ${step.done ? "checked" : ""}><input class="step-text ${step.done ? "completed" : ""}" data-step-text="${i}" value="${escape(step.text)}" maxlength="2000" placeholder="What happens next?" aria-label="Step ${i + 1}"><button type="button" data-remove-step="${i}" class="remove-small" aria-label="Remove step ${i + 1}">×</button></li>`).join("")}</ol><button type="button" id="add-step" class="secondary" ${steps.length >= 200 ? "disabled" : ""}>＋ Add step</button><p class="field-hint">Up to 200 steps.</p></section>`;
  } else if (draft.type === "table") {
    const { columns, rows } = draft.payload;
    container.innerHTML = `<section class="editor-section"><div class="section-title"><h2>Your table</h2><span>${rows.length} rows · ${columns.length} columns</span></div><div class="table-scroll"><table class="data-table"><thead><tr>${columns.map((column, i) => `<th><div><input data-column="${i}" value="${escape(column)}" maxlength="80" aria-label="Column ${i + 1} name"><button type="button" data-remove-column="${i}" class="remove-small" aria-label="Remove column ${i + 1}" ${columns.length <= 1 ? "disabled" : ""}>×</button></div></th>`).join("")}<th class="row-action"></th></tr></thead><tbody>${rows.map((row, ri) => `<tr>${row.map((cell, ci) => `<td><input data-cell="${ri},${ci}" value="${escape(cell)}" maxlength="2000" aria-label="Row ${ri + 1}, column ${ci + 1}"></td>`).join("")}<td><button type="button" data-remove-row="${ri}" class="remove-small" aria-label="Remove row ${ri + 1}">×</button></td></tr>`).join("")}</tbody></table></div><div class="table-actions"><button type="button" id="add-row" class="secondary" ${rows.length >= 200 ? "disabled" : ""}>＋ Row</button><button type="button" id="add-column" class="secondary" ${columns.length >= 12 ? "disabled" : ""}>＋ Column</button></div><p class="field-hint">1–12 columns · Up to 200 rows · Scroll sideways for more.</p></section>`;
  } else container.innerHTML = "";
}
